# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'layout_raman_window.ui'
#
# Created: Tue Apr 11 14:13:11 2017
#      by: PyQt4 UI code generator 4.11
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(1006, 686)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.groupBox_2 = QtGui.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName(_fromUtf8("groupBox_2"))
        self.gridLayout_9 = QtGui.QGridLayout(self.groupBox_2)
        self.gridLayout_9.setObjectName(_fromUtf8("gridLayout_9"))
        self.btn_prepCollect = QtGui.QPushButton(self.groupBox_2)
        self.btn_prepCollect.setObjectName(_fromUtf8("btn_prepCollect"))
        self.gridLayout_9.addWidget(self.btn_prepCollect, 1, 0, 1, 1)
        self.btn_prepObserv = QtGui.QPushButton(self.groupBox_2)
        self.btn_prepObserv.setObjectName(_fromUtf8("btn_prepObserv"))
        self.gridLayout_9.addWidget(self.btn_prepObserv, 0, 0, 1, 1)
        self.btn_prepAlign = QtGui.QPushButton(self.groupBox_2)
        self.btn_prepAlign.setObjectName(_fromUtf8("btn_prepAlign"))
        self.gridLayout_9.addWidget(self.btn_prepAlign, 2, 0, 1, 1)
        self.gridLayout.addWidget(self.groupBox_2, 1, 1, 1, 1)
        self.groupBox = QtGui.QGroupBox(self.centralwidget)
        self.groupBox.setObjectName(_fromUtf8("groupBox"))
        self.gridLayout_8 = QtGui.QGridLayout(self.groupBox)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.btn_lightOff = QtGui.QPushButton(self.groupBox)
        self.btn_lightOff.setObjectName(_fromUtf8("btn_lightOff"))
        self.gridLayout_8.addWidget(self.btn_lightOff, 1, 1, 1, 1)
        self.btn_lightOn = QtGui.QPushButton(self.groupBox)
        self.btn_lightOn.setObjectName(_fromUtf8("btn_lightOn"))
        self.gridLayout_8.addWidget(self.btn_lightOn, 1, 0, 1, 1)
        self.sld_lightSet = QtGui.QSlider(self.groupBox)
        self.sld_lightSet.setOrientation(QtCore.Qt.Horizontal)
        self.sld_lightSet.setObjectName(_fromUtf8("sld_lightSet"))
        self.gridLayout_8.addWidget(self.sld_lightSet, 2, 0, 1, 2)
        self.lb_lightstate = QtGui.QLabel(self.groupBox)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lb_lightstate.setFont(font)
        self.lb_lightstate.setText(_fromUtf8(""))
        self.lb_lightstate.setAlignment(QtCore.Qt.AlignCenter)
        self.lb_lightstate.setObjectName(_fromUtf8("lb_lightstate"))
        self.gridLayout_8.addWidget(self.lb_lightstate, 0, 0, 1, 2)
        self.gridLayout.addWidget(self.groupBox, 2, 1, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 1, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab_motors = QtGui.QWidget()
        self.tab_motors.setObjectName(_fromUtf8("tab_motors"))
        self.gridLayout_2 = QtGui.QGridLayout(self.tab_motors)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.wdgt_zoom = QtGui.QWidget(self.tab_motors)
        self.wdgt_zoom.setMinimumSize(QtCore.QSize(100, 50))
        self.wdgt_zoom.setObjectName(_fromUtf8("wdgt_zoom"))
        self.gridLayout_6 = QtGui.QGridLayout(self.wdgt_zoom)
        self.gridLayout_6.setMargin(0)
        self.gridLayout_6.setObjectName(_fromUtf8("gridLayout_6"))
        self.gridLayout_2.addWidget(self.wdgt_zoom, 0, 4, 1, 1)
        self.wdgt_diacorr = QtGui.QWidget(self.tab_motors)
        self.wdgt_diacorr.setMinimumSize(QtCore.QSize(100, 50))
        self.wdgt_diacorr.setObjectName(_fromUtf8("wdgt_diacorr"))
        self.gridLayout_5 = QtGui.QGridLayout(self.wdgt_diacorr)
        self.gridLayout_5.setMargin(0)
        self.gridLayout_5.setObjectName(_fromUtf8("gridLayout_5"))
        self.gridLayout_2.addWidget(self.wdgt_diacorr, 0, 0, 1, 1)
        self.wdgt_motors = QtGui.QWidget(self.tab_motors)
        self.wdgt_motors.setMinimumSize(QtCore.QSize(0, 50))
        self.wdgt_motors.setObjectName(_fromUtf8("wdgt_motors"))
        self.gridLayout_7 = QtGui.QGridLayout(self.wdgt_motors)
        self.gridLayout_7.setMargin(0)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.gridLayout_2.addWidget(self.wdgt_motors, 1, 0, 1, 5)
        spacerItem1 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem1, 0, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem2, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tab_motors, _fromUtf8(""))
        self.tab_festo = QtGui.QWidget()
        self.tab_festo.setObjectName(_fromUtf8("tab_festo"))
        self.gridLayout_10 = QtGui.QGridLayout(self.tab_festo)
        self.gridLayout_10.setObjectName(_fromUtf8("gridLayout_10"))
        spacerItem3 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem3, 4, 1, 1, 1)
        self.label_2 = QtGui.QLabel(self.tab_festo)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_10.addWidget(self.label_2, 1, 0, 1, 1)
        spacerItem4 = QtGui.QSpacerItem(40, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem4, 1, 6, 1, 1)
        self.taurusLabel = TaurusLabel(self.tab_festo)
        self.taurusLabel.setMinimumSize(QtCore.QSize(100, 40))
        self.taurusLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel.setObjectName(_fromUtf8("taurusLabel"))
        self.gridLayout_10.addWidget(self.taurusLabel, 0, 1, 1, 1)
        self.btn_NF_on = QtGui.QToolButton(self.tab_festo)
        self.btn_NF_on.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_NF_on.setObjectName(_fromUtf8("btn_NF_on"))
        self.gridLayout_10.addWidget(self.btn_NF_on, 2, 3, 1, 1)
        self.taurusLabel_3 = TaurusLabel(self.tab_festo)
        self.taurusLabel_3.setMinimumSize(QtCore.QSize(100, 40))
        self.taurusLabel_3.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_3.setObjectName(_fromUtf8("taurusLabel_3"))
        self.gridLayout_10.addWidget(self.taurusLabel_3, 2, 1, 1, 1)
        self.taurusLabel_2 = TaurusLabel(self.tab_festo)
        self.taurusLabel_2.setMinimumSize(QtCore.QSize(100, 40))
        self.taurusLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_2.setObjectName(_fromUtf8("taurusLabel_2"))
        self.gridLayout_10.addWidget(self.taurusLabel_2, 1, 1, 1, 1)
        self.label = QtGui.QLabel(self.tab_festo)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_10.addWidget(self.label, 0, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_festo)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_10.addWidget(self.label_3, 2, 0, 1, 1)
        self.btn_CC_on = QtGui.QToolButton(self.tab_festo)
        self.btn_CC_on.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_CC_on.setObjectName(_fromUtf8("btn_CC_on"))
        self.gridLayout_10.addWidget(self.btn_CC_on, 0, 3, 1, 1)
        self.btn_LC_on = QtGui.QToolButton(self.tab_festo)
        self.btn_LC_on.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_LC_on.setObjectName(_fromUtf8("btn_LC_on"))
        self.gridLayout_10.addWidget(self.btn_LC_on, 1, 3, 1, 1)
        self.btn_LC_off = QtGui.QToolButton(self.tab_festo)
        self.btn_LC_off.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_LC_off.setObjectName(_fromUtf8("btn_LC_off"))
        self.gridLayout_10.addWidget(self.btn_LC_off, 1, 4, 1, 1)
        self.btn_CC_off = QtGui.QToolButton(self.tab_festo)
        self.btn_CC_off.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_CC_off.setObjectName(_fromUtf8("btn_CC_off"))
        self.gridLayout_10.addWidget(self.btn_CC_off, 0, 4, 1, 1)
        self.btn_NF_off = QtGui.QToolButton(self.tab_festo)
        self.btn_NF_off.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_NF_off.setObjectName(_fromUtf8("btn_NF_off"))
        self.gridLayout_10.addWidget(self.btn_NF_off, 2, 4, 1, 1)
        self.taurusLabel_4 = TaurusLabel(self.tab_festo)
        self.taurusLabel_4.setMinimumSize(QtCore.QSize(100, 40))
        self.taurusLabel_4.setAlignment(QtCore.Qt.AlignCenter)
        self.taurusLabel_4.setObjectName(_fromUtf8("taurusLabel_4"))
        self.gridLayout_10.addWidget(self.taurusLabel_4, 3, 1, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab_festo)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_10.addWidget(self.label_4, 3, 0, 1, 1)
        self.btn_SH_on = QtGui.QToolButton(self.tab_festo)
        self.btn_SH_on.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_SH_on.setObjectName(_fromUtf8("btn_SH_on"))
        self.gridLayout_10.addWidget(self.btn_SH_on, 3, 3, 1, 1)
        self.btn_SH_off = QtGui.QToolButton(self.tab_festo)
        self.btn_SH_off.setMinimumSize(QtCore.QSize(40, 40))
        self.btn_SH_off.setObjectName(_fromUtf8("btn_SH_off"))
        self.gridLayout_10.addWidget(self.btn_SH_off, 3, 4, 1, 1)
        self.tabWidget.addTab(self.tab_festo, _fromUtf8(""))
        self.tab_calc = QtGui.QWidget()
        self.tab_calc.setObjectName(_fromUtf8("tab_calc"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab_calc)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.wv_calc = QtWebKit.QWebView(self.tab_calc)
        self.wv_calc.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wv_calc.setObjectName(_fromUtf8("wv_calc"))
        self.gridLayout_3.addWidget(self.wv_calc, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_calc, _fromUtf8(""))
        self.tab_save = QtGui.QWidget()
        self.tab_save.setObjectName(_fromUtf8("tab_save"))
        self.gridLayout_4 = QtGui.QGridLayout(self.tab_save)
        self.gridLayout_4.setMargin(0)
        self.gridLayout_4.setObjectName(_fromUtf8("gridLayout_4"))
        self.wv_save = QtWebKit.QWebView(self.tab_save)
        self.wv_save.setUrl(QtCore.QUrl(_fromUtf8("about:blank")))
        self.wv_save.setObjectName(_fromUtf8("wv_save"))
        self.gridLayout_4.addWidget(self.wv_save, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tab_save, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 4, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1006, 21))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        self.menuCalibration = QtGui.QMenu(self.menubar)
        self.menuCalibration.setObjectName(_fromUtf8("menuCalibration"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)
        self.actionCalibrate_Motors = QtGui.QAction(MainWindow)
        self.actionCalibrate_Motors.setObjectName(_fromUtf8("actionCalibrate_Motors"))
        self.menuCalibration.addAction(self.actionCalibrate_Motors)
        self.menubar.addAction(self.menuCalibration.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.menubar, QtCore.SIGNAL(_fromUtf8("triggered(QAction*)")), MainWindow.processMenuAction)
        QtCore.QObject.connect(self.btn_lightOn, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionLightOn)
        QtCore.QObject.connect(self.btn_lightOff, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionLightOff)
        QtCore.QObject.connect(self.sld_lightSet, QtCore.SIGNAL(_fromUtf8("sliderReleased()")), MainWindow.actionLightSet)
        QtCore.QObject.connect(self.btn_prepObserv, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionPrepObservation)
        QtCore.QObject.connect(self.btn_prepCollect, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionPrepCollection)
        QtCore.QObject.connect(self.btn_LC_on, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionLCon)
        QtCore.QObject.connect(self.btn_LC_off, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionLCoff)
        QtCore.QObject.connect(self.btn_CC_on, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionCCon)
        QtCore.QObject.connect(self.btn_CC_off, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionCCoff)
        QtCore.QObject.connect(self.btn_NF_on, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionNFon)
        QtCore.QObject.connect(self.btn_NF_off, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionNFoff)
        QtCore.QObject.connect(self.btn_SH_on, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionSHon)
        QtCore.QObject.connect(self.btn_SH_off, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionSHoff)
        QtCore.QObject.connect(self.btn_prepAlign, QtCore.SIGNAL(_fromUtf8("clicked()")), MainWindow.actionPrepAlignment)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.btn_prepObserv, self.btn_prepCollect)
        MainWindow.setTabOrder(self.btn_prepCollect, self.btn_prepAlign)
        MainWindow.setTabOrder(self.btn_prepAlign, self.btn_lightOn)
        MainWindow.setTabOrder(self.btn_lightOn, self.btn_lightOff)
        MainWindow.setTabOrder(self.btn_lightOff, self.sld_lightSet)
        MainWindow.setTabOrder(self.sld_lightSet, self.tabWidget)
        MainWindow.setTabOrder(self.tabWidget, self.btn_CC_on)
        MainWindow.setTabOrder(self.btn_CC_on, self.btn_CC_off)
        MainWindow.setTabOrder(self.btn_CC_off, self.btn_LC_on)
        MainWindow.setTabOrder(self.btn_LC_on, self.btn_LC_off)
        MainWindow.setTabOrder(self.btn_LC_off, self.btn_NF_on)
        MainWindow.setTabOrder(self.btn_NF_on, self.btn_NF_off)
        MainWindow.setTabOrder(self.btn_NF_off, self.btn_SH_on)
        MainWindow.setTabOrder(self.btn_SH_on, self.btn_SH_off)
        MainWindow.setTabOrder(self.btn_SH_off, self.wv_calc)
        MainWindow.setTabOrder(self.wv_calc, self.wv_save)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.groupBox_2.setTitle(_translate("MainWindow", "Fast Controls", None))
        self.btn_prepCollect.setText(_translate("MainWindow", "Prep. &Collection", None))
        self.btn_prepObserv.setText(_translate("MainWindow", "Prep. &Observation", None))
        self.btn_prepAlign.setText(_translate("MainWindow", "Prep. &Alignment", None))
        self.groupBox.setTitle(_translate("MainWindow", "Light Control", None))
        self.btn_lightOff.setText(_translate("MainWindow", "OFF", None))
        self.btn_lightOn.setText(_translate("MainWindow", "ON", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_motors), _translate("MainWindow", "Motors", None))
        self.label_2.setText(_translate("MainWindow", "Camera Cube", None))
        self.taurusLabel.setProperty("model", _translate("MainWindow", "tango://haspllabcl1:10000/llab/ramanoptics/llabcl1.01/Valve2", None))
        self.btn_NF_on.setText(_translate("MainWindow", "ON", None))
        self.taurusLabel_3.setProperty("model", _translate("MainWindow", "tango://haspllabcl1:10000/llab/ramanoptics/llabcl1.01/Valve3", None))
        self.taurusLabel_2.setProperty("model", _translate("MainWindow", "tango://haspllabcl1:10000/llab/ramanoptics/llabcl1.01/Valve1", None))
        self.label.setText(_translate("MainWindow", "Light Cube", None))
        self.label_3.setText(_translate("MainWindow", "Notch Filter", None))
        self.btn_CC_on.setText(_translate("MainWindow", "ON", None))
        self.btn_LC_on.setText(_translate("MainWindow", "ON", None))
        self.btn_LC_off.setText(_translate("MainWindow", "OFF", None))
        self.btn_CC_off.setText(_translate("MainWindow", "OFF", None))
        self.btn_NF_off.setText(_translate("MainWindow", "OFF", None))
        self.taurusLabel_4.setProperty("model", _translate("MainWindow", "tango://haspllabcl1:10000/llab/ramanoptics/llabcl1.01/Valve4", None))
        self.label_4.setText(_translate("MainWindow", "Shutter", None))
        self.btn_SH_on.setText(_translate("MainWindow", "ON", None))
        self.btn_SH_off.setText(_translate("MainWindow", "OFF", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_festo), _translate("MainWindow", "Optical Elements", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_calc), _translate("MainWindow", "Calculations Ruby", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_save), _translate("MainWindow", "Saving Positions", None))
        self.menuCalibration.setTitle(_translate("MainWindow", "Expert", None))
        self.actionCalibrate_Motors.setText(_translate("MainWindow", "Calibrate Motors", None))

from PyQt4 import QtWebKit
from taurus.qt.qtgui.display import TaurusLabel
